server:
  port: 11000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.21.108.236:3306/zmail_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ware # 微服务名，注意一定要写，否则无法被注册到Nacos中

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.zhongger.zmail: debug