spring:
  application:
    name: product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.8:3306/zmail_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.8
    port: 6379
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
        service: product # 微服务名，注意一定要写，否则无法被注册到Nacos中
  thymeleaf:
    cache: false
  cache:
    type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1  #全局的逻辑删除配置
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.zhongger.zmail: debug
alibaba:
  cloud:
    access-key: LTAI4G3JvNVddvR1Z8idZEhE
    secret-key: CACY0zkoLDHyOnTAkAL5VJ1HIsN3Kd
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com