spring:
  application:
    name: product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.7:3306/zmail_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
        service: product # 微服务名，注意一定要写，否则无法被注册到Nacos中


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.zhongger.zmail: debug

